project_id = "asmyxhisubzbblhivnea"

[functions.generate-cosmic-report]
verify_jwt = false

[functions.create-affiliate]
verify_jwt = false

[functions.track-referral]
verify_jwt = false

[functions.payout-affiliates]
verify_jwt = false

[functions.purchase-gift-certificate]
verify_jwt = false